#!/bin/sh
PREFIX=/usr/local/dowse
if ! [ -r $PREFIX/zshrc ]; then
	echo "Dowse is not installed, run 'make' and 'sudo make install' first."
	return 1
fi
ZDOTDIR=$HOME/.dowse
mkdir -p $ZDOTDIR
cat <<EOF > $ZDOTDIR/.zshrc
# local zshrc for easy start of console
# generated by dowse console.sh
# can be discarded after use
pushd $PREFIX > /dev/null
source zshrc
export PROMPT="%F{yellow}%(?..%? )%{\$reset_color%}dowse@%{\$fg[red]%}%m %{\$reset_color%}%3c %# "
EOF

ZDOTDIR=$ZDOTDIR zsh

