/* This header was automatically generated by the dowse/src/webui/map_assets script
   lun  7 nov 2016, 16.57.21, CET
 */


#include <string.h>

#include <kore.h>
#include <assets.h>

#include "hashmap.h"
#include "assetmap.h"


map_t asset_init() {
  map_t assetmap;
  asset_t atmp;
  struct kore_buf *tmp;

  assetmap = hashmap_new();

  snprintf(atmp.type, 256, "text/css");
  atmp.len  = asset_len_bootstrap_min_css;
  atmp.data = asset_bootstrap_min_css;
  tmp = kore_malloc(sizeof(asset_t));
  tmp = memcpy(tmp, &atmp, sizeof(asset_t));
  hashmap_put(assetmap, "bootstrap.min.css", tmp);


  snprintf(atmp.type, 256, "image/png");
  atmp.len  = asset_len_dowse_logo_png;
  atmp.data = asset_dowse_logo_png;
  tmp = kore_malloc(sizeof(asset_t));
  tmp = memcpy(tmp, &atmp, sizeof(asset_t));
  hashmap_put(assetmap, "dowse-logo.png", tmp);


  snprintf(atmp.type, 256, "text/x-markdown");
  atmp.len  = asset_len_HACKING_md;
  atmp.data = asset_HACKING_md;
  tmp = kore_malloc(sizeof(asset_t));
  tmp = memcpy(tmp, &atmp, sizeof(asset_t));
  hashmap_put(assetmap, "HACKING.md", tmp);


  snprintf(atmp.type, 256, "application/javascript");
  atmp.len  = asset_len_jquery_1_3_2_min_js;
  atmp.data = asset_jquery_1_3_2_min_js;
  tmp = kore_malloc(sizeof(asset_t));
  tmp = memcpy(tmp, &atmp, sizeof(asset_t));
  hashmap_put(assetmap, "jquery-1.3.2.min.js", tmp);


  snprintf(atmp.type, 256, "application/javascript");
  atmp.len  = asset_len_mqttws31_js;
  atmp.data = asset_mqttws31_js;
  tmp = kore_malloc(sizeof(asset_t));
  tmp = memcpy(tmp, &atmp, sizeof(asset_t));
  hashmap_put(assetmap, "mqttws31.js", tmp);


  snprintf(atmp.type, 256, "text/html");
  atmp.len  = asset_len_thing_show_html;
  atmp.data = asset_thing_show_html;
  tmp = kore_malloc(sizeof(asset_t));
  tmp = memcpy(tmp, &atmp, sizeof(asset_t));
  hashmap_put(assetmap, "thing_show.html", tmp);


  snprintf(atmp.type, 256, "text/html");
  atmp.len  = asset_len_things_list_html;
  atmp.data = asset_things_list_html;
  tmp = kore_malloc(sizeof(asset_t));
  tmp = memcpy(tmp, &atmp, sizeof(asset_t));
  hashmap_put(assetmap, "things_list.html", tmp);


  snprintf(atmp.type, 256, "text/html");
  atmp.len  = asset_len_websocket_html;
  atmp.data = asset_websocket_html;
  tmp = kore_malloc(sizeof(asset_t));
  tmp = memcpy(tmp, &atmp, sizeof(asset_t));
  hashmap_put(assetmap, "websocket.html", tmp);


  snprintf(atmp.type, 256, "text/html");
  atmp.len  = asset_len_welcome_html;
  atmp.data = asset_welcome_html;
  tmp = kore_malloc(sizeof(asset_t));
  tmp = memcpy(tmp, &atmp, sizeof(asset_t));
  hashmap_put(assetmap, "welcome.html", tmp);

  return(assetmap);
}

void asset_free() {
// TODO
}
