/* This header was automatically generated by the dowse/src/webui/map_assets script
   dom  6 nov 2016, 14.26.34, CET
   AND NO MORE DONE!
 */

#ifndef __ASSET_MAP_H__
#define __ASSET_MAP_H__

#include <string.h>

#include <kore.h>
#include <assets.h>

#include <libdowse/dowse.h>

typedef struct {
  char type[256];
  size_t len;
  void *data;  
} asset_t;


map_t asset_init();

#endif
