#!/usr/bin/env zsh

R=`pwd`

source ../../dowse

[[ -r debug/dnscrypt_dowse.so ]] || {
   error "dnscrypt_dowse.so not found in .libs (run make?)"
   return 1 }

notice "Test session on Dowse DNSCrypt plugin"
act "`date`"

start redis-server
start redis-volatile

act "hostname: $hostname"
act "address: $address"
act "wan: $wan"

sleep 1

cat <<EOF | redis dynamic
SET dns-lease-testlease1 10.0.0.101
SET dns-lease-testlease2 10.0.0.102
SET dns-lease-${hostname} ${address}
SET dns-reverse-10.0.0.101. testlease1
SET dns-reverse-10.0.0.102. testlease2
SET dns-reverse-${address}. ${hostname}
EOF
# SET dns-reverse-${wan}. gateway

DOWSE_DOMAINLIST=`pwd`/../domain-list/data \
				DOWSE_LAN_ADDRESS_IP4=$address \
				DOWSE_LAN_NETMASK_IP4=$netmask \
				hostname=$hostname \
				interface=$interface \
				domain=$lan	\
				valgrind --leak-check=full \--track-origins=yes \
				../dnscrypt-proxy/src/proxy/dnscrypt-proxy \
				-a $address:54540 \
				-l debug/runtests.log \
				-L ../dnscrypt-proxy/dnscrypt-resolvers.csv \
				-R "ipredator" \
				-X `pwd`/debug/dnscrypt_dowse.so,debug \
				-m 7 -d
# log level informational (7 for debug)


sleep 3

notice own_hostname
act "dig @$address -p 54540 $hostname"
dig @$address -p 54540 $hostname

notice own_address_reverse
act "dig @$address -p 54540 -x $address"
dig @$address -p 54540 -x $address

# run tests offline

# notice dyne.org
# dig @$address -p 54540 dyne.org || return 1

# notice dnssec.vs.uni-due.de
# dig @$address -p 54540 sigok.verteiltesysteme.net || return 1

notice 10.0.0.101
act "dig @$address -p 54540 -x 10.0.0.101"
dig @$address -p 54540 -x 10.0.0.101

notice 10.0.0.102
act "dig @$address -p 54540 -x 10.0.0.102"
dig @$address -p 54540 -x 10.0.0.102

notice testlease1
act "dig @$address -p 54540 testlease1"
dig @$address -p 54540 testlease1

notice testlease2
act "dig @$address -p 54540 testlease2.dowse.it"
dig @$address -p 54540 testlease2.dowse.it

notice gateway
act "dig @$address -p 54540 gateway"
dig @$address -p 54540 gateway


notice "dnscrypt-plugin - all tests OK"
return 0

