#!/usr/bin/env zsh

R=`pwd`

[[ -r ../../zuper/zuper ]] || {
   print "usage: ./debug/valgrind (run from inside src/dnscrypt-plugin)"
   return 1 }

source ../../zuper/zuper

source ../../zuper/zuper.init

[[ -r .libs/dnscrypt_dowse.so ]] || {
   error "dnscrypt_dowse.so not found in .libs (run make?)"
   return 1 }

notice "Valgrind debug session on Debugging"
act "`date`"

DOWSE_DOMAINLIST=$HOME/devel/dowse/src/domain-list/data \
				DOWSE_LAN_ADDRESS_IP4=127.0.0.1 \
				hostname=$hostname \
				domain=$lan \
			    valgrind --leak-check-heuristics=all --show-leak-kinds=all --track-origins=yes \
				../dnscrypt-proxy/src/proxy/dnscrypt-proxy \
				-a 127.0.0.1:53530 \
				-l debug/valgrind.log \
				-r "178.216.201.222:2053" \
				-k "25C4:E188:2915:4697:8F9C:2BBD:B6A7:AFA4:01ED:A051:0508:5D53:03E7:1928:C066:8F21" \
				-N "2.dnscrypt-cert.soltysiak.com" \
				-X $R/.libs/dnscrypt_dowse.so,cache,debug,$1 \
				-m 7
# log level informational (7 for debug)

