.TH SUP 1 sup\-1.0
.SH NAME
sup - a "small is beautiful" tool for UNIX privilege escalation
.SH SYNOPSIS
.B sup
.RB [ \-hlv ]
.SH DESCRIPTION
sup is a very small and secure C application. it is designed to run as root (with suid bit on) to facilitate the privilege escalation of users to execute certain programs as superuser.
.P
all settings in sup are hard-coded at compile time. sup is very portable and self-contained, designed for production use as a static binary. sup is a sort of hard-coded sudo: it is an ideal companion for artisans building small containers and embedded systems.
.SH OPTIONS
.TP
.B \-h
print help message
.TP
.B \-l
list configuration
.TP
.B \-v
print version information
.SH AUTHOR
sup is copyleft software licensed as GNU Lesser Public License
(LGPLv3). when compiled with the HASH flag on its license turns
into GNU GPLv2 because of the sha256 component.
.P
sup is copyleft (c) 2009-2011 by pancake of nopcode.org
.BR
                (c) 2016      by jaromil of dyne.org
.P
the FIPS-180-2 sha-256 implementation optionally included in sup is
copyleft (c) 2001-2003 by Christophe Devine
