#!/usr/bin/zsh

source $R/env

# Remove any address/route from $interface
ip addr flush dev $interface

# Can fail here
modprobe br_netfilter

# If any fatal error happens, cleanup the bridge (it will also set an address
# and a route to $interface, so the device can still be accessed on the network)
ip link add $bridge type bridge || ( bridge_cleanup; error "Failed to create bridge" )
ip link set $bridge up || ( bridge_cleanup; error "Failed to bring bridge up" )

ip link set $interface master $bridge || ( bridge_cleanup; \
		error "Failed to link $interface with $bridge" )

ip addr add $wan_network_address dev $bridge || ( bridge_cleanup; \
		error "Failed to add address $wan_network_address to $bridge" )

ip route add default via ${wan_default_gateway[(ws:/:)1]} dev $bridge || \
		( bridge_cleanup; \
		error "Failed to add route to $wan_network_address for $bridge" )

