#!/usr/bin/env zsh
#
# Copyright (C) 2015-2016 Dyne.org Foundation
#
# Dowse is designed, written and maintained by Denis Roio <jaromil@dyne.org>
#
# This source code is free software; you can redistribute it
# and/or modify it under the terms of the GNU Public License
# as published by the Free Software Foundation; either
# version 3 of the License, or (at your option) any later
# version.
#
# This source code is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
# PURPOSE.  Please refer to the GNU Public License for more
# details.
#
# You should have received a copy of the GNU Public License
# along with this source code; if not, write to: Free
# Software Foundation, Inc., 675 Mass Ave, Cambridge, MA
# 02139, USA.

source $R/env

cat <<EOF > /run/dowse/conf/mosquitto.conf
pid_file /run/dowse/mosquitto.pid
user dowse
# bind_address $address

listener 1883
protocol mqtt

listener 1888
protocol websockets

log_dest file /var/log/dowse/mosquitto.log
# websockets_log_level 0
# connection_messages true
allow_anonymous true
EOF

if [[ $DEBUG = 1 ]]; then
	exec mosquitto -c /run/dowse/conf/mosquitto.conf -v
else
	exec mosquitto -c /run/dowse/conf/mosquitto.conf
fi

