#!/usr/bin/zsh

source $R/env

cat <<EOF > /run/dowse/conf/netdata.conf
[global]
    # special port for dowse
    port = 29999
    ip version = ipv4
    bind socket to ip = 127.0.0.1

    run as user = dowse
    web files owner = root
    web files group = root

    lib directory = /var/lib/dowse/netdata

    error log  = /var/log/dowse/netdata-error.log
    access log = /var/log/dowse/netdata-access.log
    debug log  = /var/log/dowse/netdata-debug.log

    memory deduplication = yes
    # save - dump on exit
    # map  - write to disk realtime
    memory mode = ram

[plugins]
	tc = no
	idlejitter = no
	cgroups = no
	checks = no
	apps = no
	node.d = no

[plugin:proc]
        /proc/diskstats = no
        /proc/net/ip_vs/stats = no
        /proc/vmstat = no
        /proc/net/rpc/nfsd = no
        /proc/interrupts = no
        /proc/softirqs = no
        /sys/kernel/mm/ksm = no

[plugin:proc:/proc/stat]
        cpu interrupts = no

[plugin:proc:/proc/meminfo]
        system swap = no

EOF

# check if required dirs exist
mkdir -p /var/lib/dowse/netdata/registry
chown -R dowse:dowse /var/lib/dowse/
mkdir -p /var/lib/dowse/cache/netdata
chown dowse:dowse /var/log/dowse/

pid=/run/dowse/netdata.pid
exec netdata -D -P $pid -c /run/dowse/conf/netdata.conf -p 29999

