#!/usr/bin/env zsh

source $R/env

timefile="/run/dowse/pendulum_nmap_timefile"
# Execute nmap after one minute has passed since the last run
snooze -S"*" "-M*" "-H*" -t $timefile -T 1m \
		sh -c "$R/pendulum nmap; touch $timefile"

