#!/usr/bin/env zsh

# also see:
# $R/run/pgl/lib/pgl/pglcmd.defaults
# $R/run/pgl/lib/pgl/pglcmd.main

pglcmd-conf() {
    fn pgl-conf

    cat <<EOF
LOCAL_BLOCKLIST_DIR="$R/conf/blocklists"
BLOCKLISTS_LIST=""
ALLOW_IN="$R/conf/whitelist.p2p"
ALLOW_OUT="$R/conf/whitelist.p2p"
LOGDIR="$R/log"
DAEMON_LOG="\${LOGDIR}/pgld.log"
WD="0"
EOF

}

pglcmd-exec() {
    fn pgl-start
    $R/run/sup $R/run/pgl/bin/pglcmd start
}

pglcmd-kill() {
    fn pgl-stop
    $R/run/sup $R/run/pgl/bin/pglcmd stop
}
