#!/usr/bin/env zsh

# also see:
# $R/run/pgl/lib/pgl/pglcmd.defaults
# $R/run/pgl/lib/pgl/pglcmd.main

pglcmd-conf() {
    fn pgl-conf

    cat <<EOF
LOCAL_BLOCKLIST_DIR="$H/conf/blocklists"
BLOCKLISTS_LIST=""
ALLOW_IN="$H/conf/whitelist.p2p"
ALLOW_OUT="$H/conf/whitelist.p2p"
LOGDIR="$H/log"
DAEMON_LOG="\${LOGDIR}/pgld.log"
WD="0"
EOF

}

pglcmd-exec() {
    fn pglcmd-start $*
    $R/bin/sup $R/bin/pglcmd start
}

pglcmd-kill() {
    fn pglcmd-stop
    $R/bin/sup $R/bin/pglcmd stop
}
