#!/usr/bin/env zsh

source $R/env

# also see:
# $R/run/pgl/lib/pgl/pglcmd.defaults
# $R/run/pgl/lib/pgl/pglcmd.main

cat <<EOF > $R/etc/pgl/pglcmd.conf
LOCAL_BLOCKLIST_DIR="/etc/dowse/blocklists"
BLOCKLISTS_LIST=""
ALLOW_IN="/etc/dowse/whitelist.p2p"
ALLOW_OUT="/etc/dowse/whitelist.p2p"
LOGDIR="/var/log/dowse"
DAEMON_LOG="\${LOGDIR}/pgld.log"
WD="0"
EOF

$R/bin/pglcmd start

