#!/usr/bin/env zsh
#
# Copyright (C) 2012-2015 Dyne.org Foundation
#
# Dowse is written and maintained by Denis Roio <jaromil@dyne.org>
#
# This source code is free software; you can redistribute it
# and/or modify it under the terms of the GNU Public License
# as published by the Free Software Foundation; either
# version 3 of the License, or (at your option) any later
# version.
#
# This source code is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
# PURPOSE.  Please refer to the GNU Public License for more
# details.
#
# You should have received a copy of the GNU Public License
# along with this source code; if not, write to: Free
# Software Foundation, Inc., 675 Mass Ave, Cambridge, MA
# 02139, USA.

seccrond-conf() {
	fn seccrond-conf
	cat <<EOF
*/50 * * * * * $R/bin/pendulum nmap
*/15 * * * * * $R/bin/pendulum netscan
*/10 * * * * * $R/bin/pendulum watchdog
*/1 * * * * * $R/bin/pendulum nextcmd
EOF
}

seccrond-exec() {
	fn seccrond-exec
	freq=($conf)
	ckreq || return $?

	func "Clean the lock"
	lock_list=(watchdog nextcmd nmap netscan)
	for i in $lock_list ; do
	    print "DEL lock_$i " | redis runtime
	done

	#---
	launch seccrond -f $conf -p $H/run/seccrond.pid
	savepid seccrond $H/run/seccrond.pid
}
