#!/usr/bin/env zsh

tor-extract() {
    fn tor-extract

    # check if already imported
    [[ -r $R/run/tor ]] && return 0

    deb-download tor

    cp $R/tmp/usr/bin/tor $R/run \
        || {
        erorro "tor binary not found"
        return 1 }

    act "tor binary imported"
    func "`ls $R/tmp`"

    rm -rf $R/tmp

    func "`file $R/run/tor`"
}

tor-conf() {
    fn tor-conf

    [[ -z $root ]] || {
        cat <<EOF
User $dowse_uid
EOF
    }

    cat <<EOF
PidFile $R/run/tor.pid
SocksPolicy accept 127.0.0.1
SocksPolicy accept $address
SocksPolicy reject *
Log notice file $R/log/tor.log
RunAsDaemon 1
DataDirectory $R/run
CookieAuthentication 1
ExitPolicy reject *:*
EOF

}

tor-start() {
    fn tor-start
    conf=$1
    freq=($conf)
    ckreq || return 0

    act "launching tor"

    $R/run/tor -f $conf
}

tor-stop() {
    fn tor-stop
    pidfile=$1
    freq=($pidfile)
    ckreq || return 0

    pid=`cat $pidfile`
    act "Stopping tor ($pid)"
    kill $pid
    waitpid $pid
    rm -f $pidfile

}
