#!/usr/bin/env zsh

tor-conf() {
    fn tor-conf

    [[ -z $root ]] || {
        cat <<EOF
User $dowse_uid
EOF
    }

    cat <<EOF
PidFile $R/run/tor.pid
SocksPolicy accept 127.0.0.1
SocksPolicy accept $address
SocksPolicy reject *
Log notice file $R/log/tor.log
RunAsDaemon 1
DataDirectory $R/run
CookieAuthentication 1
ExitPolicy reject *:*
EOF

}

tor-exec() {
    fn tor-exec $*
    execpath=${1:-${execmap[tor]}}
    conf=$1
    req=(execpath)
    freq=($conf)
    ckreq || return 0

    act "launching tor"

    $execpath -f $conf
}

tor-kill() {
    fn tor-stop
    pidfile=$1
    freq=($pidfile)
    ckreq || return 0

    pid=`cat $pidfile`
    act "Stopping tor ($pid)"
    kill $pid
    waitpid $pid
    rm -f $pidfile

}
