#!/usr/bin/env zsh

webdis-conf() {
    fn webdis-conf $*
    cat << EOF
{
    "redis_host":   "127.0.0.1",

    "redis_port":   6379,
    "redis_auth":   null,

    "http_host":    "$address",
    "http_port":    7379,

    "threads":  2,
    "pool_size": 5,

    "daemonize":    true,
    "websockets":   true,

    "database": ${db[dynamic]},
    "pidfile": "$H/run/webdis.pid",

    "acl": [
        { "disabled":   ["DEBUG"] },
        { "http_basic_auth":    "user:password",
          "enabled":        ["DEBUG"] }
    ],

    "verbosity": 6,
    "logfile": "$H/log/webdis.log"
}
EOF
}

webdis-exec() {
    fn webdis-exec $*
    req=(conf)
    freq=($conf)
    ckreq || return $?

    launch webdis $conf
    savepid webdis $H/run/webdis.pid
}
