#!/usr/bin/zsh

source $R/env

func "launching webui2 on $hostname.$lan"

if [[ $DEBUG = 2 ]]; then
	hostname=$hostname \
			domain=$lan \
			address=$address \
			interface=$interface \
			exec python3 $R/src/webui2/webui.py
else
	hostname=$hostname \
			domain=$lan \
			address=$address \
			interface=$interface \
			exec python3 $R/src/webui2/webui.py \
			-p /run/dowse/webui2.pid 1>/dev/null 2>/dev/null
fi

