#!/usr/bin/env zsh

dowse_mod_name=squid-privoxy
dowse_mod_desc="Transparent http proxy pipeline chaining squid to privoxy"
dowse_mod_type=(http proxy)
dowse_mod_ports=(squid/3128 privoxy/8118)
dowse_mod_deps=(squid privoxy)
dowse_mod_authors=(Jaromil)
dowse_mod_version=0.1

# setup a transparent proxy on port 80
# using squid and privoxy
module-setup() {

    squid-conf > $R/run/squid.conf
    cat <<EOF >> $R/run/squid.conf
http_port $address:3128 transparent
http_port 3129
pid_filename $R/run/squid.pid
cache_log $R/log/squid_cache.log
access_log stdio:/dev/null
# access_log $R/log/squid_access.log squid
# pass through privoxy
cache_peer $address parent 8118 0 default no-query no-digest no-netdb-exchange proxy-only
EOF

    privoxy-conf > $R/run/privoxy.conf
    cat <<EOF >> $R/run/privoxy.conf
logdir $R/log/privoxy.log
pid-file $R/run/privoxy.pid
listen-address  0.0.0.0:8118
EOF

}

module-start() {

    [[ $EUID = 0 ]] && {
        notice "setup transparent proxy to squid"
        iptables -t nat -A PREROUTING -i $interface -s $dowse_net \
            -p tcp --dport 80 -j REDIRECT --to-port 3128
        iptables -A INPUT -p tcp --dport 3128 -j ACCEPT

    }

    privoxy-start $R/run/privoxy.conf

    squid-start $R/run/squid.conf

}

module-stop() {

    squid-stop $R/run/squid.pid

    privoxy-stop $R/run/privoxy.pid

}
