#!/usr/bin/env zsh

deb-download() {
    fn deb-download $*
    deb="$1"
    req=(deb)

    ckreq || return 1

    mkdir -p $R/tmp
    [[ $? = 0 ]] || {
        error "cannot create $R/tmp"
        return 1 }

    pushd $R/tmp > /dev/null

    apt-get -q download $deb
    [[ $? = 0 ]] || {
        error "error downloading $deb"
        return 1 }

    debfile=`find . -name "${deb}_*.deb"`

    popd > /dev/null

    freq=($R/tmp/$debfile)
    ckreq || return 1

    act "extracting $R/tmp/$debfile"
    dpkg -x $R/tmp/$debfile $R/tmp
    [[ $? = 0 ]] || {
        error "error extracting $R/tmp/$debfile"
        return 1 }

    return 0
}
