#!/usr/bin/zsh

check_ap_capabilities() {
	interface=$1
	for i in $(seq 0 5); do
		# https://stackoverflow.com/questions/17988756/how-to-select-lines-between-two-marker-patterns-which-may-occur-multiple-times-w
		# Get all interfaces for physical device phy#$i
		interfaces=$(iw dev | awk "/phy#$i/{flag=1;next}/phy#$((i+1))/{flag=0}/Interface/{if(flag==1){print \$2}}")
		for dev in "$interfaces"; do
			# Until we have found the interface we needed
			if [[ "$dev" == "$interface" ]]; then
				physical_dev="phy$i"
				break
			fi
		done
	done

	# Then check if the phisical device has AP capabilities
	if [[ "$(iw phy $physical_dev info | grep 'AP$')" != "" ]]; then
		echo 1
	fi

	echo 0
}

get_wifi_interfaces() {
	wifi_interfaces=$(iw dev | awk '/Interface/ { print $2 }')

	echo "$wifi_interfaces[@]"
}

get_ap_real_interface() {
	all_interfaces=$(get_wifi_interfaces)

	for dev in $all_interfaces ; do
		if [[ $(check_ap_capabilities $dev) ]]; then
			echo $dev
			echo 1
		fi
	done
	echo 0
}

get_ap_virtual_interfaces() {
	virtual_interfaces=()
	for (( i = 1; i <= $#ssid; i++ )) do
		if [[ "" == "$ssid[$i]" ]]; then
			continue
		fi
		virtual_interfaces+=" dowse_wifi$i"
	done

	echo ${virtual_interfaces[@]}
}

