#!/usr/bin/zsh

redis() {

    _db="${db[$1]}"
    req=(_db)
    ckreq || return 1

	cat | launch redis-cli -n $_db --raw
    [[ $? = 0 ]] && {
		# success
		return 0
	}

	error "failure sending commands to redis db $_db"
	return 1

}
