#!/usr/bin/zsh

redis() {
	local db
    db="$1"
    req=(db)
    ckreq || return 1

    case "$db" in
		runtime|dynamic)
			launch redis-cli -h 127.0.0.1 -p 6378 --raw
			;;
		storage)
			launch redis-cli -h 127.0.0.1 -p 6379 --raw
			;;
	esac

    [[ $? = 0 ]] && {
		# success
		return 0
	}

	error "failure sending commands to redis $db"
	return 1

}
