#!/usr/bin/env zsh

dowse_mod_name=tor-privoxy
dowse_mod_desc="Tor gateway using privoxy"
dowse_mod_tags=(proxy anon)
dowse_mod_ports=(tor:9050 tor:9051 privoxy:9119)
dowse_mod_daemons=(tor privoxy)
dowse_mod_authors=(jaromil)
dowse_mod_version=0.2

module-setup() {

    tor-conf > $R/run/tor.conf
cat <<EOF >> $R/run/tor.conf
SocksPort 127.0.0.1:9050
ControlPort 9051
EOF

    privoxy-conf > $R/run/privoxy-tor.conf
    cat <<EOF >> $R/run/privoxy-tor.conf
listen-address $address:9119
logdir $R/log/privoxy-tor.log
pid-file $R/run/privoxy-tor.pid

forward-socks5 / 127.0.0.1:9050 .

# pass .onion urls directly through tor
#forward-socks4a .onion 127.0.0.1:9050 .
EOF
}

module-start() {
    tor-start $R/run/tor.conf
    privoxy-start $R/run/privoxy-tor.conf
    # tor drops privileges to uid set in config
}

module-stop() {
    tor-stop $R/run/tor.pid
    privoxy-stop $R/run/privoxy-tor.pid
}
