Vagrant.configure(2) do |config|
  config.vm.box = "http://vagrant.devuan.org/devuan-jessie-amd64-alpha2.box"
  config.ssh.username = "root"
  config.ssh.password = "devuan"
  config.vm.guest = :debian
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.network :public_network

  config.vm.network "forwarded_port", guest: 67, host: 67, protocol: 'udp'
  config.vm.network "forwarded_port", guest: 68, host: 68, protocol: 'udp'

  config.vm.define "leader", primary: true do |leader|
   leader.vm.network "private_network", ip: "192.168.0.254", auto_config: false
    leader.vm.provision "ansible" do |ansible|
      ansible.playbook = "dowse.yml"
      ansible.sudo = true
    end
  end

  config.vm.define "client" do |client|
   client.vm.network "private_network", ip: "192.168.0.250", auto_config: false
   client.vm.provision :shell, inline: 'route del default eth0 && rm -f /var/lib/dhcp/dhclient.eth2.leases && dhclient eth2'
  end
end
