Vagrant.configure(2) do |config|
  config.vm.box = "https://files.devuan.org/devuan_jessie_beta/testing/devuan_jessie_1.0.0-beta2_amd64_vagrant.box"
  config.ssh.username = "root"
  config.ssh.password = "toor"
  config.vm.guest = :debian
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.network :public_network

  config.vm.network "forwarded_port", guest: 67, host: 67, protocol: 'udp'
  config.vm.network "forwarded_port", guest: 68, host: 68, protocol: 'udp'

  config.vm.define "leader", primary: true do |leader|
   leader.vm.network "private_network", ip: "192.168.0.254", auto_config: false
   leader.vm.provision "shell", path: "dowse_install.sh"
  end

  config.vm.define "client" do |client|
   client.vm.network "private_network", ip: "192.168.0.250", auto_config: false
   client.vm.provision :shell, inline: 'route del default eth0 && rm -f /var/lib/dhcp/dhclient.eth2.leases && dhclient eth2'
  end
end
