Vagrant.configure(2) do |config|
  config.vm.box = "http://vagrant.devuan.org/devuan-jessie-amd64-alpha2.box"
  config.ssh.username = "root"
  config.ssh.password = "devuan"
  config.vm.guest = :debian
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.network :public_network

  config.vm.define "leader", primary: true do |leader|
   leader.vm.network "private_network", ip: "192.168.0.254", auto_config: false
    leader.vm.provision "ansible" do |ansible|
      ansible.playbook = "dowse.yml"
      ansible.sudo = true
    end
  end

  config.vm.define "client" do |client|
   client.vm.network "private_network", ip: "192.168.0.101", auto_config: false
    client.vm.provision :shell, inline: 'route del default gw 10.0.2.2 && dhclient -v eth1'
  end
end
